<a name='1.1'></a>
### 1.1 - System of Linear Equations

Here is a **system of linear equations** (or **linear system**) with three equations and three unknown variables:


$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

**To solve** this system of linear equations means to find such values of the variables $x_1$, $x_2$, $x_3$, that all of its equations are simultaneously satisfied.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))
print(A)
print(b)

[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
[-10.   0.  17.]


In [5]:
b_reshaped = b.reshape(3,1)


print(A)
print(b_reshaped)


[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
[[-10.]
 [  0.]
 [ 17.]]


In [6]:
#find the determinant of A
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -60.000000000000036


In [7]:
#now solve the equation 
res = np.linalg.solve(A, b_reshaped)
print("Solution:", res)

Solution: [[ 1.]
 [ 4.]
 [-2.]]
